postgres:
  image: postgres:9.3
  ports:
  - "5432:5432"
  volumes:
  - /vagrant/backups:/backups

elasticsearch:
  image: elasticsearch:1.4
  ports:
  - "9200:9200"

redis:
  image: redis:2.8
  ports:
  - "6379:6379"

memcached:
  image: memcached:1.4
  ports:
  - "11211:11211"

nginx:
  image: nginx
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - /vagrant/etc/nginx/sites:/etc/nginx/conf.d
  - /vagrant/etc/nginx/certs:/etc/nginx/certs
  - /vagrant/demo_project:/app
  # HACK: allows the container to share the host networking stack,
  # so we can reference the app as localhost.
  net: host
